local module = {
	Pulse = {
		ExtraInfo = {
			MaxLevel = 5,
			Bullet = {
				[1] = { "Start" },
				[2] = { "Start" },
				[3] = { "Start" },
				[4] = { "Start", "Start2" },
				[5] = { "Start3" },
			},
			Hidden = { 3, 4, 5 },
			Class = {
				[1] = "Pulse",
				[2] = "Pulse",
				[3] = "Pulse",
				[4] = "Pulse",
				[5] = "Pulse",
			},
			Pulse = {
				[1] = {
					Amount = 10,
					Shots = 8,
					Cooldown = 8,
				},
				[2] = {
					Amount = 10,
					Shots = 8,
					Cooldown = 8,
				},
				[3] = {
					Amount = 10,
					Shots = 10,
					Cooldown = 8,
				},
				[4] = {
					Amount = 20,
					Shots = 12,
					Cooldown = 7,
				},
				[5] = {
					Amount = 30,
					Shots = 15,
					Cooldown = 6,
				},
			},
			Effect = "Bullet",
		},
		[1] = {
			Cooldown = 0.8,
			Range = 13,
			Damage = 2, --2
			Price = 175,
			Name = "Pulse",
		},
		[2] = {
			LevelName = "THIS IS TESTING BRANCH DATA!!",
			Cooldown = 0.8,
			Range = 15,
			Damage = 3,
			Price = 100,
			Name = "Pulse",
			Invisible = { 1 },
			Animation = 1,
			Exclude = {
				"Head acc",
				"Left Leg acc",
				"Right Leg acc",
				"Torso acc",
			},
		},
		[3] = {
			LevelName = "Communication",
			Cooldown = 0.75,
			Range = 19,
			Damage = 6,
			Price = 400,
			Name = "Pulse",
			Invisible = { 2 },
			Animation = 1,
			UpgradeUp = {
				"Handle",
				"Handle 2",
			},
			Exclude = {
				"Right Arm acc",
				"Left Arm acc",
			},

			["Pulse Bar : Duration"] = {
				Value = 10,
				Colour = Color3.new(0.317647, 0.945098, 1),
				Format = "Pulse Duration: %d Shots.",
				MustShow = true,
			},
		},
		[4] = {
			LevelName = "Biker Clothes and A New Buddy",
			Cooldown = 0.375,
			Range = 19,
			Damage = 6,
			Price = 800,
			Name = "Pulse",
			Invisible = { 3 },
			Animation = 2,
			OrderedAnimations = 2, -- Max Value of animation to cycle
			Exclude = {
				"Head acc",
			},
			["Pulse Bar"] = {
				Value = 20,
				Colour = Color3.new(0.317647, 0.945098, 1),
				Format = "Pulse Bar Requirement : %d Shots.",
				MustShow = true,
			},
			["Pulse Bar : Duration"] = {
				Value = 12,
				Colour = Color3.new(0.317647, 0.945098, 1),
				Format = "Pulse Duration: %d Shots.",
				MustShow = true,
			},
			["Pulse Bar : Cooldown"] = {
				Value = 7,
				Colour = Color3.new(0.317647, 0.945098, 1),
				Format = "Pulse Cooldown: %d Seconds.",
				MustShow = true,
			},
		},
		[5] = {
			LevelName = "Night-Vision Googles and new Kit",
			Cooldown = 0.155,
			Range = 21,
			Damage = 6,
			Price = 1800,
			Name = "Pulse",
			Animation = 4,
			Invisible = { 4 },
			RemoveInTable = {
				"OrderedAnimations",
				"OrderedAnimationsCurrentCycle",
				"SpeedUpCorrectly",
			},
			["Pulse Bar"] = {
				Value = 30,
				Colour = Color3.new(0.317647, 0.945098, 1),
				Format = "Pulse Bar Requirement : %d Shots.",
				MustShow = true,
			},
			["Pulse Bar : Duration"] = {
				Value = 15,
				Colour = Color3.new(0.317647, 0.945098, 1),
				Format = "Pulse Duration: %d Shots.",
				MustShow = true,
			},
			["Pulse Bar : Cooldown"] = {
				Value = 6,
				Colour = Color3.new(0.317647, 0.945098, 1),
				Format = "Pulse Cooldown: %d Seconds.",
				MustShow = true,
			},
		},
	},

	Barrage = {
		ExtraInfo = {
			MaxLevel = 6,
			Cone = true,
			Shotgun = {
				[1] = { "Start" },
				[2] = { "Start" },
				[3] = { "Start1" },
				[4] = { "Start2" },
				[5] = { "Start2" },
				[6] = { "Start2" },
			},
			Hidden = { 6 },
			Class = {
				[1] = "Single",
				[2] = "Single",
				[3] = "Single",
				[4] = "Single",
				[5] = "Single",
				[6] = "Single",
			},
			Effect = "Shotgun",
		},
		[1] = {
			Cooldown = 2,
			Range = 5,
			Damage = 4,
			Price = 500,
			Penetration = {
				Value = 25,
				Colour = Color3.new(1, 1, 1),
				Format = "Penetration: %d%% of tower range.",
				MustShow = true,
			},
			["Spread Angle"] = {
				Value = 26,
				Colour = Color3.new(1, 0.666667, 0),
				Format = "Spread Angle: %d°.",
				MustShow = true,
			},
			["Drop Off Damage"] = {
				Value = 15,
				Colour = Color3.new(1, 0, 0),
				Format = "Damage Drop Off: %d%% per 0.5 studs of penetration range.",
				MustShow = true,
			},
			Name = "Barrage",
		},
		[2] = {
			LevelName = "Extra Training",
			Cooldown = 1.6,
			Range = 5,
			Damage = 4,
			Price = 300,
			Name = "Barrage",
			Penetration = {
				Value = 25,
				Colour = Color3.new(1, 1, 1),
				Format = "Penetration: %d%% of tower range.",
			},
			["Spread Angle"] = {
				Value = 26,
				Colour = Color3.new(1, 0.666667, 0),
				Format = "Spread Angle: %d°.",
			},
			["Drop Off Damage"] = {
				Value = 15,
				Colour = Color3.new(1, 0, 0),
				Format = "Damage Drop Off: %d%% per 0.5 studs of penetration range.",
				MustShow = true,
			},
			Invisible = { 1 },
		},
		[3] = {
			LevelName = "New Firepower",
			Cooldown = 1.5,
			Range = 5.5,
			Damage = 6,
			Price = 500,
			Name = "Barrage",
			Invisible = { 2 },
			Animation = 2,

			Penetration = {
				Value = 35,
				Colour = Color3.new(1, 1, 1),
				Format = "Penetration: %d%% of tower range.",
			},
			["Spread Angle"] = {
				Value = 30,
				Colour = Color3.new(1, 0.666667, 0),
				Format = "Spread Angle: %d°.",
			},
			["Drop Off Damage"] = {
				Value = 12.5,
				Colour = Color3.new(1, 0, 0),
				Format = "Damage Drop Off: %d%% per 0.5 studs of penetration range.",
				MustShow = true,
			},
		},
		[4] = {
			LevelName = "New Attachments",
			Cooldown = 1.4,
			Range = 6,
			Damage = 10,
			Price = 650,
			Animation = 4,
			Name = "Barrage",

			Penetration = {
				Value = 45,
				Colour = Color3.new(1, 1, 1),
				Format = "Penetration: %d%% of tower range.",
			},
			["Spread Angle"] = {
				Value = 35,
				Colour = Color3.new(1, 0.666667, 0),
				Format = "Spread Angle: %d°.",
			},
			["Drop Off Damage"] = {
				Value = 10,
				Colour = Color3.new(1, 0, 0),
				Format = "Damage Drop Off: %d%% per 0.5 studs of penetration range.",
				MustShow = true,
			},

			Invisible = { 3 },
		},
		[5] = {
			LevelName = "Full Training",
			Cooldown = 0.9,
			Range = 6.5,
			Damage = 22,
			Price = 1900,
			Name = "Barrage",
			Animation = 4,
			Invisible = { 4 },
			Exclude = {
				"Torso acc1 lv4",
				"Prop lv4",
				"Pump lv4",
			},

			Penetration = {
				Value = 50,
				Colour = Color3.new(1, 1, 1),
				Format = "Penetration: %d%% of tower range.",
			},
			["Spread Angle"] = {
				Value = 35,
				Colour = Color3.new(1, 0.666667, 0),
				Format = "Spread Angle: %d°.",
			},
			["Drop Off Damage"] = {
				Value = 10,
				Colour = Color3.new(1, 0, 0),
				Format = "Damage Drop Off: %d%% per 0.5 studs of penetration range.",
				MustShow = true,
			},
		},
		[6] = {
			LevelName = "Heavy Equipment",
			Cooldown = 0.8,
			Range = 7,
			Damage = 25,
			Price = 2250,
			Animation = 4,
			Name = "Barrage",
			Invisible = { 5, 4, 3, 2, 1 },
			Exclude = {
				"Torso acc1 lv4",
				"Prop lv4",
				"Pump lv4",
			},
			Penetration = {
				Value = 100,
				Colour = Color3.new(1, 1, 1),
				Format = "Penetration: %d%% of tower range.",
			},
			["Spread Angle"] = {
				Value = 40,
				Colour = Color3.new(1, 0.666667, 0),
				Format = "Spread Angle: %d°.",
			},
			["Drop Off Damage"] = {
				Value = 7.5,
				Colour = Color3.new(1, 0, 0),
				Format = "Damage Drop Off: %d%% per 0.5 studs of penetration range.",
				MustShow = true,
			},
		},
	},

	Vesper = {
		ExtraInfo = {
			MaxLevel = 5,
			HighGround = true,
			Bullet = {
				[1] = { "Start" },
				[2] = { "Start" },
				[3] = { "Start1" },
				[4] = { "Start2" },
				[5] = { "Start3" },
			},
			Air = { 1,2,3,4,5 },
			Hidden = { 1,2,3,4,5 },
			Class = {
				[1] = "Single",
				[2] = "Single",
				[3] = "Single",
				[4] = "Single",
				[5] = "Single",
			},
			Effect = "Bullet",
		},
		[1] = {
			Cooldown = 3.75,
			Range = 26,
			Damage = 15,
			Price = 375,
			Name = "Vesper",
			["Armour Penetration"] = {
				Value = 15,
				Colour = Color3.new(1, 0, 0),
				Format = "Shield Penetration: %d%%.",
				MustShow = true,
			},
		},
		[2] = {
			LevelName = "Better Grip",
			Cooldown = 3.6,
			Range = 28,
			Damage = 28,
			Price = 500,
			Name = "Vesper",
			Invisible = { 1 },
			["Armour Penetration"] = {
				Value = 20,
				Colour = Color3.new(1, 0, 0),
				Format = "Shield Penetration: %d%%.",
				MustShow = true,
			},
		},
		[3] = {
			LevelName = "Scope Attachment",
			Cooldown = 3.45,
			Range = 33,
			Damage = 45,
			Price = 975,
			Name = "Vesper",
			Invisible = { 2 },
			["Armour Penetration"] = {
				Value = 25,
				Colour = Color3.new(1, 0, 0),
				Format = "Shield Penetration: %d%%.",
				MustShow = true,
			},
		},
		[4] = {
			LevelName = "New Weapon kit",
			Cooldown = 3.2,
			Range = 39,
			Damage = 90,
			Price = 2000,
			Name = "Vesper",
			Invisible = { 3 },
			Animation = 3,
			["Armour Penetration"] = {
				Value = 30,
				Colour = Color3.new(1, 0, 0),
				Format = "Shield Penetration: %d%%.",
				MustShow = true,
			},
		},
		[5] = {
			LevelName = "New kit",
			Cooldown = 2.8,
			Range = 41,
			Damage = 195,
			Price = 4150,
			Name = "Vesper",
			Invisible = { 4 },
			Animation = 4,
			["Armour Penetration"] = {
				Value = 30,
				Colour = Color3.new(1, 0, 0),
				Format = "Shield Penetration: %d%%.",
				MustShow = true,
			},
		},
	},

	Moonfall = {
		ExtraInfo = {
			MaxLevel = 5,
			Class = {
				[1] = "Single",
				[2] = "Single",
				[3] = "Single",
				[4] = "Single",
				[5] = "Single",
			},
			Hidden = { 3, 4, 5 },
			Effect = "Moonfall",
		},
		[1] = {
			Cooldown = 1.4,
			Range = 5,
			Damage = 8,
			Price = 400,
			Name = "Moonfall",
			DisplayName = "Aella",
			RandomAttackAnimation = 4,
			SpeedUpCorrectly = true,
			Invisible = {},
			Burn = {
				Value = 1,
				Format = "Burns %d%% of enemy HP (Min: 1, Max: 180) per second for 5 seconds. (50%% Shield Penetration)",
				Colour = Color3.new(1, 0.666667, 0.498039),
			},
			["Spread Angle"] = {
				Value = 25,
				Colour = Color3.new(0.227450, 0.560784, 1),
				Format = "Spread Angle: %d°.",
			},
		},
		[2] = {
			LevelName = "Order: Lone Wanderer",
			Cooldown = 1.2,
			Range = 5.5,
			Damage = 10,
			Price = 525,
			Name = "Moonfall",
			DisplayName = "Aella",
			RandomAttackAnimation = 4,
			SpeedUpCorrectly = true,
			Invisible = {},
			Burn = {
				Value = 1,
				Format = "Burns %d%% of enemy HP (Min: 1, Max: 180) per second for 5 seconds. (50%% Shield Penetration)",
				Colour = Color3.new(1, 0.666667, 0.498039),
			},
			["Spread Angle"] = {
				Value = 25,
				Colour = Color3.new(0.227450, 0.560784, 1),
				Format = "Spread Angle: %d°.",
			},
		},
		[3] = {
			LevelName = "Attuned: First Officer",
			Cooldown = 1,
			Range = 6,
			Damage = 20,
			Price = 1050,
			Name = "Moonfall",
			DisplayName = "Aella",
			RandomAttackAnimation = 4,
			Invisible = {},
			Burn = {
				Value = 2.5,
				Colour = Color3.new(1, 0.666667, 0.498039),
				Format = "Burns %d%% of enemy HP (Min: 1, Max: 180) per second for 5 seconds. (50%% Shield Penetration)",
			},
			["Spread Angle"] = {
				Value = 30,
				Colour = Color3.new(0.227450, 0.560784, 1),
				Format = "Spread Angle: %d°.",
			},
		},
		[4] = {
			LevelName = "Ascendant: Polemarch",
			Cooldown = 0.9,
			Range = 6.5,
			Damage = 40,
			Price = 3500,
			Name = "Moonfall",
			DisplayName = "Aella",
			RandomAttackAnimation = 4,
			SpeedUpCorrectly = true,
			Invisible = {},
			Burn = {
				Value = 5,
				Colour = Color3.new(1, 0.666667, 0.498039),
				Format = "Burns %d%% of enemy HP (Min: 1, Max: 180) per second for 5 seconds. (50%% Shield Penetration)",
			},
			["Spread Angle"] = {
				Value = 30,
				Colour = Color3.new(0.227450, 0.560784, 1),
				Format = "Spread Angle: %d°.",
			},
		},
		[5] = {
			LevelName = "Zenith: Archon",
			Cooldown = 0.8,
			Range = 8,
			Damage = 55,
			Price = 8000,
			Name = "Moonfall",
			DisplayName = "Aella",
			Invisible = { 3 },
			Exclude = {
				"Head Visor",
				"Head Visor Neon",
				"Head Visor Headset",
				"Head Visor Headset Neon",
			},
			RandomAttackAnimation = 4,
			SpeedUpCorrectly = true,
			Burn = {
				Value = 10,
				Colour = Color3.new(1, 0.666667, 0.498039),
				Format = "Burns %d%% of enemy HP (Min: 1, Max: 180) per second for 5 seconds. (50%% Shield Penetration)",
			},
			["Spread Angle"] = {
				Value = 45,
				Colour = Color3.new(0.227450, 0.560784, 1),
				Format = "Spread Angle: %d°.",
			},
		},
	},

	Exterminator = {
		ExtraInfo = {
			MaxLevel = 5,
			Bullet = {
				[1] = { "Start" },
				[2] = { "Start" },
				[3] = { "Start" },
				[4] = { "Start1" },
				[5] = { "Start2" },
			},
			Hidden = { 3, 4, 5 },
			Class = {
				[1] = "Single",
				[2] = "Single",
				[3] = "Single",
				[4] = "Single",
				[5] = "Single",
			},
			Effect = "Bullet",
		},

		[1] = {
			Cooldown = 0.48,
			Range = 15,
			Damage = 12,
			Price = 3500,
			Name = "Exterminator",
		},
		[2] = {
			LevelName = "Googles!",
			Cooldown = 0.48,
			Range = 16,
			Damage = 18,
			Price = 1500,
			Name = "Exterminator",
			Invisible = { 1 },
			Exclude = {
				"Handle lv0",
				"Handle2 lv0",
				"Handle3 lv0",
			},
		},
		[3] = {
			LevelName = "New small kit",
			Cooldown = 0.48,
			Range = 16,
			Damage = 35,
			Price = 3500,
			Name = "Exterminator",
			Invisible = { 2 },
		},
		[4] = {
			LevelName = "Now that's a whole new kit!",
			Cooldown = 0.358,
			Range = 18,
			Damage = 45,
			Price = 6500,
			Name = "Exterminator",
			Invisible = { 3 },
			Animation = 3,
		},
		[5] = {
			LevelName = "New Military Advancement",
			Cooldown = 0.22,
			Range = 22,
			Damage = 50,
			Price = 10000,
			Name = "Exterminator",
			Invisible = { 4 },
			Animation = 4,
		},
	},

	Blitzkrieg = {
		ExtraInfo = {
			MaxLevel = 5,
			Hidden = {  4, 5 },
			Class = {
				[1] = "Single",
				[2] = "Single",
				[3] = "Single",
				[4] = "Single",
				[5] = "Single",
			},
			Explosion = {
				[1] = { Effect = "NormalExplosion", Speed = 0.5, Grenade = "BlitzGrenade0", Sound = "SmallExplosion", AOE = 3 },
				[2] = { Effect = "NormalExplosion", Speed = 0.5, Grenade = "BlitzGrenade0", Sound = "SmallExplosion", AOE = 4 },
				[3] = { Effect = "BigExplosion", Speed = 0.4, Grenade = "BlitzGrenade2", Sound = "Explosion", AOE = 6 },
				[4] = { Effect = "BigExplosion", Speed = 0.3, Grenade = "BlitzGrenade2", Sound = "Explosion", AOE = 6 },
				[5] = { Effect = "BigExplosion", Speed = 0.25, Grenade = "BlitzGrenade2", Sound = "BigExplosion", AOE = 7 },
			},
			Effect = "Explosion",
		},
		[1] = {
			Cooldown = 3.15,
			Range = 7,
			Damage = 6,
			Price = 450,
			["Explosion Range"] = {
				Value = 3,
				Colour = Color3.new(1, 0.666667, 0.498039),
				Format = "Explosion Radius: %d studs.",
			},
			Name = "Blitzkrieg",
		},
		[2] = {
			LevelName = "New Gears",
			Cooldown = 2.5,
			Range = 8,
			Damage = 8,
			Price = 300,
			Name = "Blitzkrieg",
			Invisible = { 1 },
			Exclude = {
				"Head acc",
				"Left Leg acc",
				"Right Leg acc",
				"Torso acc",
				"Weapon",
				"Handle",
			},
			["Explosion Range"] = {
				Value = 4,
				Colour = Color3.new(1, 0.666667, 0.498039),
				Format = "Explosion Radius: %d studs.",
			},
		},
		[3] = {
			LevelName = "Funni green ball go boom boom",
			Cooldown = 2.3,
			Range = 11,
			Damage = 18,
			Price = 1050,
			Name = "Blitzkrieg",
			Invisible = { 1, 2 },
			Exclude = {
				"Head acc",
				"Left Leg acc",
				"Right Leg acc",
				"Left Arm acc",
				"Right Arm acc",
				"Torso acc",
			},
			["Explosion Range"] = {
				Value = 6,
				Colour = Color3.new(1, 0.666667, 0.498039),
				Format = "Explosion Radius: %d studs.",
			},
		},
		[4] = {
			LevelName = "New Power Set",
			Cooldown = 2.3,
			Range = 15,
			Damage = 46,
			Price = 2700,
			["Explosion Range"] = {
				Value = 7,
				Colour = Color3.new(1, 0.666667, 0.498039),
				Format = "Explosion Radius: %d studs.",
			},
			Name = "Blitzkrieg",
			Invisible = { 1, 2, 3 },
			Exclude = {
				"Head acc",
				"Weapon",
			},
			["Armour Penetration"] = {
				Value = 10,
				Colour = Color3.new(1, 0, 0),
				Format = "Shield Penetration: %d%%.",
				MustShow = true,
			},
		},
		[5] = {
			LevelName = "Oh this can shoot pretty far",
			Cooldown = 0.55,
			Range = 18,
			Damage = 28,
			Price = 6900,
			["Explosion Range"] = {
				Value = 6,
				Colour = Color3.new(1, 0.666667, 0.498039),
				Format = "Explosion Radius: %d studs.",
			},
			Animation = 4,
			Name = "Blitzkrieg",
			Invisible = { 4, 3, 2, 1},
			Exclude = {
				"Left Arm acc",
				"Left Leg acc",
				"Right Leg acc",
				"Right Arm acc",
			},
		},
	},

	Skylight = {
		ExtraInfo = {
			MaxLevel = 5,
			HighGround = true,
			SkylightBeam = {
				[1] = { "Start" },
				[2] = { "Start" },
				[3] = { "Start" },
				[4] = { "Start1" },
				[5] = { "Start2" },
			},
			Air = { 1, 2, 3, 4 , 5},
			Hidden = { 4, 5	 },
			Class = {
				[1] = "Single",
				[2] = "Single",
				[3] = "Single",
				[4] = "Single",
				[5] = "Single",
			},
			Effect = "SkylightBeam",
		},
		[1] = {
			Cooldown = 6,
			Range = 50,
			Damage = 200,
			Price = 5000,
			Name = "Skylight",

			["Kinetic Accretion"] = {
				Value = 0.1,
				Colour = Color3.new(0.317647, 0.945098, 1),
				Format = "Kinetic Accretion: +%.1f%% per stud.",
				MustShow = true,
			},
		},
		[2] = {
			LevelName = "Better suited dealing with Atherion-83",
			Cooldown = 5,
			Range = 50,
			Damage = 200,
			Price = 1350,
			Name = "Skylight",
			Invisible = { },

			["Kinetic Accretion"] = {
				Value = 0.1,
				Colour = Color3.new(0.317647, 0.945098, 1),
				Format = "Kinetic Accretion: +%.1f%% per stud.",
				MustShow = true,
			},
		},
		[3] = {
			LevelName = "Homemade Googles and Atherion Flux Discharge !!",
			Cooldown = 4,
			Range = 50,
			Damage = 250,
			Price = 4150,
			Name = "Skylight",
			Invisible = { },

			["Kinetic Accretion"] = {
				Value = 0.1,
				Colour = Color3.new(0.317647, 0.945098, 1),
				Format = "Kinetic Accretion: +%.1f%% per stud.",
				MustShow = true,
			},
		},
		[4] = {
			LevelName = "Aetherion Unified Discharge System",
			Cooldown = 8,
			Range = 75,
			Damage = 1000,
			Price = 10000,
			Name = "Skylight",
			Invisible = { 1 },
			Animation = 3,

			["Kinetic Accretion"] = {
				Value = 0.25,
				Colour = Color3.new(0.317647, 0.945098, 1),
				Format = "Kinetic Accretion: +%.1f%% per stud.",
				MustShow = true,
			},

			["Progressive Ionisation"] = {
				Value = 0.15,
				Colour = Color3.new(0.388235, 0.003921, 0.415686),
				Format = "Progressive Ionisation: Enemy takes more damage from Skylight's beam every time it gets hit by Skylight. (Each stack adds %.2f%%) (Max: 50 stacks for damage).",
				MustShow = true,
			},

			["Layered Rupture"] = {
				Value = 10,
				Colour = Color3.new(0.780392, 0.490196, 1),
				Format = "Layered Rupture: Each %d ionisation stack melts enemy's shield by 1%%. (Max: 20%%)"
			},

			["Critical Ion Density"] = {
				Value = 300,
				Colour = Color3.new(0.235294, 0, 0.235294),
				Format = "Critical Ion Density: Once the enemy has been defeated and has been charged due to progressive ionisation, it will outburst energy dealing %d with a base range of 4 studs. (+0.2%% range and 1%% damage per ionisation stack)"
			},
		},
		[5] = {
			LevelName = "Skylight: The Convergence",
			Cooldown = 16,
			Range = 75,
			Damage = 4500,
			Price = 25000,
			Name = "Skylight",
			Invisible = { 4 },
			Exclude = {
				"Circle1",
				"square",
				"PointLight",
			},
			Animation = 4,

			["Kinetic Accretion"] = {
				Value = 0.5,
				Colour = Color3.new(0.317647, 0.945098, 1),
				Format = "Kinetic Accretion: +%.1f%% per stud.",
				MustShow = true,
			},

			["Progressive Ionisation"] = {
				Value = 0.30,
				Colour = Color3.new(0.388235, 0.003921, 0.415686),
				Format = "Progressive Ionisation: Enemy takes more damage from Skylight's beam every time it gets hit by Skylight. (Each stack adds %.2f%%) (Max: 50 stacks for damage).",
				MustShow = true,
			},
		},
	},

	Anomaly = {
		ExtraInfo = {
			MaxLevel = 5,
			Class = {
				[1] = "Single",
				[2] = "Single",
				[3] = "Single",
				[4] = "Single",
				[5] = "Single",
			},
			Bullet = {
				[1] = {"Start", "Start2"},
				[2] = {"Start", "Start2"},
				[3] = {"Start", "Start2"},
				[4] = {"Start", "Start2"},
				[5] = {"Start", "Start2"},
			},
			Effect = "Bullet",
		},
		[1] = {
			Cooldown = 0.25,
			Range = 12,
			Damage = 1,
			Price = 500,
			Name = "Anomaly",
			OrderedAnimations = 2,
		},
		[2] = {
			LevelName = "(?)",
			Cooldown = 0.18,
			Range = 15,
			Damage = 2,
			Price = 450,
			Invisible = {},
			Name = "Anomaly",
			OrderedAnimations = 2,
		},
		[3] = {
			LevelName = "(?)",
			Cooldown = 0.13,
			Range = 18,
			Damage = 8,
			Price = 1855,
			Invisible = {},
			Name = "Anomaly",
			OrderedAnimations = 2,
		},
		[4] = {
			LevelName = "(?)",
			Cooldown = 0.1,
			Range = 20,
			Damage = 12,
			Price = 2750,
			Invisible = {},
			Name = "Anomaly",
			OrderedAnimations = 2,
		},
		[5] = {
			LevelName = "(?)",
			Cooldown = 0.05,
			Range = 25,
			Damage = 20,
			Price = 5000,
			Invisible = {},
			Name = "Anomaly",
			OrderedAnimations = 2,
		},
	},

	Dealer = {
		ExtraInfo = {
			MaxLevel = 5,
			MaxPlacement = 6, 
			Hidden = {2,3,4,5},
			Class = {
				[1] = "Single",
				[2] = "Single",
				[3] = "Single",
				[4] = "Single",
				[5] = "Single",
			},
			Bullet = {
				[1] = {"Start"},
				[2] = {"Start"},
				[3] = {"Start"},
				[4] = {"Start2"},
				[5] = {"Start3"},
			},
			Dealer = {
				DamageDealtOnWave = 0,
				[1] = {
					FixedIncome = 35,
					Multiplier = 0.5,
				},
				[2] = {
					FixedIncome = 55,
					Multiplier = 0.7,
				},
				[3] = {
					FixedIncome = 145,
					Multiplier = 0.85,
				},
				[4] = {
					FixedIncome = 180,
					Multiplier = 0.85,
				},
				[5] = {
					FixedIncome = 100,
					Multiplier = 1,
				},
			},
			Effect = "Bullet",
		},
		[1] = {
			Cooldown = 1,
			Range = 10,
			Damage = 2,
			Price = 550,
			Name = "Dealer",
			["Rates"] = {
				Value = 50,
				Colour = Color3.new(0.152941, 0.894117, 0.486274),
				Format = "Rates: %d%% of damage done per wave"
			},
			["Fixed Rates"] = {
				Value = 70,
				Colour = Color3.new(0.078431, 0.360784, 0.098039),
				Format = "Fixed Rates: %d Money per wave."
			},
		},
		[2] = {
			Cooldown = 0.85,
			Range = 15,
			Damage = 3,
			Price = 450,

			LevelName = "Expanding Network",
			Invisible = {},
			Name = "Dealer",
			["Rates"] = {
				Value = 70,
				Colour = Color3.new(0.152941, 0.894117, 0.486274),
				Format = "Rates: %d%% of damage done per wave"
			},
			["Fixed Rates"] = {
				Value = 55,
				Colour = Color3.new(0.078431, 0.360784, 0.098039),
				Format = "Fixed Rates: %d Money per wave."
			},
		},
		[3] = {
			Cooldown = 0.75,
			Range = 15,
			Damage = 5,
			Price = 900,

			LevelName = "Lucrative Contracts",
			Invisible = { 1 },
			Exclude = {
				"Vest",
				"GunHandle",
				"Gun1Body",
				"CaseBody",
				"CaseBody2",
				"CaseHandle",
				"CaseHandle2",
			},
			Name = "Dealer",
			["Rates"] = {
				Value = 85,
				Colour = Color3.new(0.152941, 0.894117, 0.486274),
				Format = "Rates: %d%% of damage done per wave"
			},
			["Fixed Rates"] = {
				Value = 145,
				Colour = Color3.new(0.078431, 0.360784, 0.098039),
				Format = "Fixed Rates: %d Money per wave."
			},
		},
		[4] = {
			Cooldown = 0.6,
			Range = 15,
			Damage = 10,
			Price = 2700,

			LevelName = "Business Expansion",
			Invisible = { 1 },
			Exclude = {
				"Vest",
				"CaseBody",
				"CaseBody2",
				"CaseHandle",
				"CaseHandle2",
			},
			Name = "Dealer",
			["Fixed Rates"] = {
				Value = 180,
				Colour = Color3.new(0.078431, 0.360784, 0.098039),
				Format = "Fixed Rates: %d Money per wave."
			},
		},
		[5] = {
			Cooldown = 0.2,
			Range = 17,
			Damage = 10,
			Price = 9000,

			LevelName = "Compound Investments",
			Invisible = { 1, 4 },
			Exclude = {
				"Fedora"
			},
			Name = "Dealer",
			["Rates"] = {
				Value = 100,
				Colour = Color3.new(0.152941, 0.894117, 0.486274),
				Format = "Rates: %d%% of damage done per wave"
			},
			["Fixed Rates"] = {
				Value = 100,
				Colour = Color3.new(0.078431, 0.360784, 0.098039),
				Format = "Fixed Rates: %d Money per wave."
			},
		},
	},

	None = {
		["ExtraInfo"] = {
			["MaxLevel"] = 1,
		},
		[1] = {
			["Cooldown"] = 0,
			["Range"] = 0,
			["Damage"] = 0,
			["Price"] = 0,
			["Name"] = "None",
		},
	},
}

return module
