local module = {
	Pulse = {
		ExtraInfo = {
			MaxLevel = 5,
			Bullet = {
				[1] = { "Start" },
				[2] = { "Start" },
				[3] = { "Start" },
				[4] = { "Start", "Start2" },
				[5] = { "Start3" },
			},
			Hidden = { 4, 5 },
			Class = {
				[1] = "Single",
				[2] = "Single",
				[3] = "Single",
				[4] = "Single",
				[5] = "Single",
			},
			Effect = "Bullet",
		},
		[1] = {
			Cooldown = 0.8,
			Range = 13,
			Damage = 2,
			Price = 175,
			Name = "Pulse",
		},
		[2] = {
			LevelName = "Gloves!!",
			Cooldown = 0.8,
			Range = 15,
			Damage = 3,
			Price = 100,
			Name = "Pulse",
			Invisible = { 1 },
			Animation = 1,
			Exclude = {
				"Head acc",
				"Left Leg acc",
				"Right Leg acc",
				"Torso acc",
			},
		},
		[3] = {
			LevelName = "Communication",
			Cooldown = 0.75,
			Range = 19,
			Damage = 6,
			Price = 400,
			Name = "Pulse",
			Invisible = { 2 },
			Animation = 1,
			UpgradeUp = {
				"Handle",
				"Handle 2",
			},
			Exclude = {
				"Right Arm acc",
				"Left Arm acc",
			},
		},
		[4] = {
			LevelName = "Biker Clothes and A New Buddy",
			Cooldown = 0.375,
			Range = 19,
			Damage = 6,
			Price = 800,
			Name = "Pulse",
			Invisible = { 3 },
			Animation = 2,
			OrderedAnimations = 2, -- Max Value of animation to cycle
			SpeedUpCorrectly = true,
			Exclude = {
				"Head acc",
			},
		},
		[5] = {
			LevelName = "Night-Vision Googles and new Kit",
			Cooldown = 0.155,
			Range = 21,
			Damage = 6,
			Price = 1800,
			Name = "Pulse",
			Animation = 4,
			Invisible = { 4 },
			RemoveInTable = {
				"OrderedAnimations",
				"OrderedAnimationsCurrentCycle",
				"SpeedUpCorrectly",
			}
		},
	},

	Barrage = {
		ExtraInfo = {
			MaxLevel = 6,
			Cone = true,
			Shotgun = {
				[1] = { "Start" },
				[2] = { "Start" },
				[3] = { "Start1" },
				[4] = { "Start2" },
				[5] = { "Start2" },
				[6] = { "Start2" },
			},
			Hidden = { 6 },
			Class = {
				[1] = "Single",
				[2] = "Single",
				[3] = "Single",
				[4] = "Single",
				[5] = "Single",
				[6] = "Single",
			},
			Effect = "Shotgun",
		},
		[1] = {
			Cooldown = 2,
			Range = 7,
			Damage = 4,
			Price = 500,
			Penetration = {
				Value = 10,
				Colour = Color3.new(1, 1, 1),
				Format = "Penetration: %d%% of tower range.",
			},
			["Spread Angle"] = {
				Value = 26,
				Colour = Color3.new(1, 0.666667, 0),
				Format = "Spread Angle: %d°.",
			},
			Name = "Barrage",
		},
		[2] = {
			LevelName = "Extra Training",
			Cooldown = 1.6,
			Range = 7,
			Damage = 4,
			Price = 300,
			Name = "Barrage",
			Penetration = {
				Value = 10,
				Colour = Color3.new(1, 1, 1),
				Format = "Penetration: %d%% of tower range.",
			},
			["Spread Angle"] = {
				Value = 26,
				Colour = Color3.new(1, 0.666667, 0),
				Format = "Spread Angle: %d°.",
			},
			Invisible = { 1 },
		},
		[3] = {
			LevelName = "New Firepower",
			Cooldown = 1.5,
			Range = 7.5,
			Damage = 6,
			Price = 500,
			Name = "Barrage",
			Invisible = { 2 },
			Animation = 2,

			Penetration = {
				Value = 20,
				Colour = Color3.new(1, 1, 1),
				Format = "Penetration: %d%% of tower range.",
			},
			["Spread Angle"] = {
				Value = 30,
				Colour = Color3.new(1, 0.666667, 0),
				Format = "Spread Angle: %d°.",
			},
		},
		[4] = {
			LevelName = "New Attachments",
			Cooldown = 1.4,
			Range = 8,
			Damage = 10,
			Price = 650,
			Animation = 4,
			Name = "Barrage",

			Penetration = {
				Value = 40,
				Colour = Color3.new(1, 1, 1),
				Format = "Penetration: %d%% of tower range.",
			},
			["Spread Angle"] = {
				Value = 35,
				Colour = Color3.new(1, 0.666667, 0),
				Format = "Spread Angle: %d°.",
			},

			Invisible = { 3 },
		},
		[5] = {
			LevelName = "Full Training",
			Cooldown = 0.9,
			Range = 8,
			Damage = 22,
			Price = 1900,
			Name = "Barrage",
			Animation = 4,
			Invisible = { 4 },
			Exclude = {
				"Torso acc1 lv4",
				"Prop lv4",
				"Pump lv4",
			},

			Penetration = {
				Value = 40,
				Colour = Color3.new(1, 1, 1),
				Format = "Penetration: %d%% of tower range.",
			},
			["Spread Angle"] = {
				Value = 35,
				Colour = Color3.new(1, 0.666667, 0),
				Format = "Spread Angle: %d°.",
			},
		},
		[6] = {
			LevelName = "Heavy Equipment",
			Cooldown = 0.8,
			Range = 9,
			Damage = 25,
			Price = 2250,
			Animation = 4,
			Name = "Barrage",
			Invisible = { 5, 4, 3, 2, 1 },
			Exclude = {
				"Torso acc1 lv4",
				"Prop lv4",
				"Pump lv4",
			},
			Penetration = {
				Value = 100,
				Colour = Color3.new(1, 1, 1),
				Format = "Penetration: %d%% of tower range.",
			},
			["Spread Angle"] = {
				Value = 40,
				Colour = Color3.new(1, 0.666667, 0),
				Format = "Spread Angle: %d°.",
			},
		},
	},

	Vesper = {
		ExtraInfo = {
			MaxLevel = 5,
			HighGround = true,
			Bullet = {
				[1] = { "Start" },
				[2] = { "Start" },
				[3] = { "Start1" },
				[4] = { "Start2" },
				[5] = { "Start3" },
			},
			Air = { 1,2,3,4,5 },
			Hidden = { 1,2,3,4,5 },
			Class = {
				[1] = "Single",
				[2] = "Single",
				[3] = "Single",
				[4] = "Single",
				[5] = "Single",
			},
			Effect = "Bullet",
		},
		[1] = {
			Cooldown = 3.75,
			Range = 26,
			Damage = 15,
			Price = 375,
			Name = "Vesper",
		},
		[2] = {
			LevelName = "Better Grip",
			Cooldown = 3.6,
			Range = 28,
			Damage = 28,
			Price = 500,
			Name = "Vesper",
			Invisible = { 1 },
		},
		[3] = {
			LevelName = "Scope Attachment",
			Cooldown = 3.45,
			Range = 33,
			Damage = 45,
			Price = 975,
			Name = "Vesper",
			Invisible = { 2 },
		},
		[4] = {
			LevelName = "New Weapon kit",
			Cooldown = 3.2,
			Range = 39,
			Damage = 90,
			Price = 2000,
			Name = "Vesper",
			Invisible = { 3 },
			Animation = 3,
			["Armour Penetration"] = {
				Value = 15,
				Colour = Color3.new(1, 0, 0),
				Format = "Armour Penetration: %d%%. (If you can see this, it means Hydro has not added this. Either she forgot to add it or forgot to remove this. Remind her)",
			},
		},
		[5] = {
			LevelName = "New kit",
			Cooldown = 2.8,
			Range = 41,
			Damage = 195,
			Price = 4150,
			Name = "Vesper",
			Invisible = { 4 },
			Animation = 4,
			["Armour Penetration"] = {
				Value = 15,
				Colour = Color3.new(1, 0, 0),
				Format = "Armour Penetration: %d%%. (If you can see this, it means Hydro has not added this. Either she forgot to add it or forgot to remove this. Remind her)",
			},
		},
	},

	Moonfall = {
		ExtraInfo = {
			MaxLevel = 5,
			Class = {
				[1] = "Single",
				[2] = "Single",
				[3] = "Single",
				[4] = "Single",
				[5] = "Single",
			},
			Hidden = { 3, 4, 5 },
			Effect = "Moonfall",
		},
		[1] = {
			Cooldown = 1.4,
			Range = 5,
			Damage = 8,
			Price = 400,
			Name = "Moonfall",
			DisplayName = "Aella",
			RandomAttackAnimation = 4,
			SpeedUpCorrectly = true,
			Invisible = {},
			Burn = {
				Value = 1,
				Format = "Burns %d%% of enemy HP (Min: 1, Max: 180) per second for 5 seconds.",
				Colour = Color3.new(1, 0.666667, 0.498039),
			},
		},
		[2] = {
			LevelName = "Order: Lone Wanderer",
			Cooldown = 1.2,
			Range = 5.5,
			Damage = 10,
			Price = 525,
			Name = "Moonfall",
			DisplayName = "Aella",
			RandomAttackAnimation = 4,
			SpeedUpCorrectly = true,
			Invisible = {},
			Burn = {
				Value = 1,
				Format = "Burns %d%% of enemy HP (Min: 1, Max: 180) per second for 5 seconds.",
				Colour = Color3.new(1, 0.666667, 0.498039),
			},
		},
		[3] = {
			LevelName = "Attuned: First Officer",
			Cooldown = 1,
			Range = 6,
			Damage = 20,
			Price = 1050,
			Name = "Moonfall",
			DisplayName = "Aella",
			RandomAttackAnimation = 4,
			Invisible = {},
			Burn = {
				Value = 2.5,
				Colour = Color3.new(1, 0.666667, 0.498039),
				Format = "Burns %d%% of enemy HP (Min: 1, Max: 180) per second for 5 seconds.",
			},
		},
		[4] = {
			LevelName = "Ascendant: Polemarch",
			Cooldown = 0.9,
			Range = 6.5,
			Damage = 40,
			Price = 3500,
			Name = "Moonfall",
			DisplayName = "Aella",
			RandomAttackAnimation = 4,
			SpeedUpCorrectly = true,
			Invisible = {3},
			Burn = {
				Value = 5,
				Colour = Color3.new(1, 0.666667, 0.498039),
				Format = "Burns %d%% of enemy HP (Min: 1, Max: 180) per second for 5 seconds.",
			},
		},
		[5] = {
			LevelName = "Zenith: Archon",
			Cooldown = 0.8,
			Range = 8,
			Damage = 55,
			Price = 8000,
			Name = "Moonfall",
			DisplayName = "Aella",
			Invisible = { },
			Exclude = {
				"Head Visor",
				"Head Visor Neon",
				"Head Visor Headset",
				"Head Visor Headset Neon",
			},
			RandomAttackAnimation = 4,
			SpeedUpCorrectly = true,
			Burn = {
				Value = 10,
				Colour = Color3.new(1, 0.666667, 0.498039),
				Format = "Burns %d%% of enemy HP (Min: 1, Max: 180) per second for 5 seconds.",
			},
		},
	},

	Exterminator = {
		ExtraInfo = {
			MaxLevel = 5,
			Bullet = {
				[1] = { "Start" },
				[2] = { "Start" },
				[3] = { "Start" },
				[4] = { "Start1" },
				[5] = { "Start2" },
			},
			Hidden = { 3, 4, 5 },
			Class = {
				[1] = "Single",
				[2] = "Single",
				[3] = "Single",
				[4] = "Single",
				[5] = "Single",
			},
			Effect = "Bullet",
		},

		[1] = {
			Cooldown = 0.48,
			Range = 15,
			Damage = 12,
			Price = 3500,
			Name = "Exterminator",
		},
		[2] = {
			LevelName = "Googles!",
			Cooldown = 0.48,
			Range = 16,
			Damage = 18,
			Price = 1500,
			Name = "Exterminator",
			Invisible = { 1 },
			Exclude = {
				"Handle lv0",
				"Handle2 lv0",
				"Handle3 lv0",
			},
		},
		[3] = {
			LevelName = "New small kit",
			Cooldown = 0.48,
			Range = 16,
			Damage = 35,
			Price = 3500,
			Name = "Exterminator",
			Invisible = { 2 },
		},
		[4] = {
			LevelName = "Now that's a whole new kit!",
			Cooldown = 0.358,
			Range = 18,
			Damage = 45,
			Price = 6500,
			Name = "Exterminator",
			Invisible = { 3 },
			Animation = 3,
		},
		[5] = {
			LevelName = "New Military Advancement",
			Cooldown = 0.22,
			Range = 22,
			Damage = 50,
			Price = 10000,
			Name = "Exterminator",
			Invisible = { 4 },
			Animation = 4,
		},
	},

	Blitzkrieg = {
		ExtraInfo = {
			MaxLevel = 5,
			Class = {
				[1] = "Single",
				[2] = "Single",
				[3] = "Single",
				[4] = "Single",
				[5] = "Single",
			},
			Explosion = {
				[1] = { Effect = "NormalExplosion", Speed = 0.5, Grenade = "BlitzGrenade0", Sound = "SmallExplosion", AOE = 3 },
				[2] = { Effect = "NormalExplosion", Speed = 0.5, Grenade = "BlitzGrenade0", Sound = "SmallExplosion", AOE = 4 },
				[3] = { Effect = "BigExplosion", Speed = 0.4, Grenade = "BlitzGrenade2", Sound = "Explosion", AOE = 6 },
				[4] = { Effect = "BigExplosion", Speed = 0.3, Grenade = "BlitzGrenade2", Sound = "Explosion", AOE = 6 },
				[5] = { Effect = "BigExplosion", Speed = 0.25, Grenade = "BlitzGrenade2", Sound = "BigExplosion", AOE = 7 },
			},
			Effect = "Explosion",
		},
		[1] = {
			Cooldown = 3,
			Range = 7,
			Damage = 8,
			Price = 500,
			["Explosion Range"] = {
				Value = 3,
				Colour = Color3.new(1, 0.666667, 0.498039),
				Format = "Explosion Radius: %d studs.",
			},
			Name = "Blitzkrieg",
		},
		[2] = {
			LevelName = "New Gears",
			Cooldown = 2.7,
			Range = 8,
			Damage = 8,
			Price = 650,
			Name = "Blitzkrieg",
			Invisible = { 1 },
			Exclude = {
				"Head acc",
				"Left Leg acc",
				"Right Leg acc",
				"Torso acc",
				"Weapon",
				"Handle",
				"Headlight Point",
			},
			["Explosion Range"] = {
				Value = 4,
				Colour = Color3.new(1, 0.666667, 0.498039),
				Format = "Explosion Radius: %d studs.",
			},
		},
		[3] = {
			LevelName = "Funni green ball go boom boom",
			Cooldown = 2.3,
			Range = 9,
			Damage = 14,
			Price = 2500,
			Name = "Blitzkrieg",
			Invisible = { 2 },
			Exclude = {
				"Head acc",
				"Left Leg acc",
				"Right Leg acc",
				"Torso acc",
				"Headlight Point",
			},
			["Explosion Range"] = {
				Value = 6,
				Colour = Color3.new(1, 0.666667, 0.498039),
				Format = "Explosion Radius: %d studs.",
			},
		},
		[4] = {
			LevelName = "New Power Set",
			Cooldown = 2.3,
			Range = 13,
			Damage = 14,
			Price = 3000,
			["Explosion Range"] = {
				Value = 6,
				Colour = Color3.new(1, 0.666667, 0.498039),
				Format = "Explosion Radius: %d studs.",
			},
			Name = "Blitzkrieg",
			Invisible = { 1, 2, 3 },
			Exclude = {
				"Weapon",
			},
		},
		[5] = {
			LevelName = "Oh this can shoot pretty far",
			Cooldown = 2,
			Range = 20,
			Damage = 34,
			Price = 5000,
			["Explosion Range"] = {
				Value = 7,
				Colour = Color3.new(1, 0.666667, 0.498039),
				Format = "Explosion Radius: %d studs.",
			},
			Animation = 4,
			Name = "Blitzkrieg",
			Invisible = { 4, 3, 2, 1},
			Exclude = {
				"Left Arm acc",
				"Left Leg acc",
				"Right Leg acc",
				"Right Arm acc",
			},
		},
	},

	Skylight = {
		ExtraInfo = {
			MaxLevel = 5,
			HighGround = true,
			SkylightBeam = {
				[1] = { "Start" },
				[2] = { "Start" },
				[3] = { "Start1" },
				[4] = { "Start2" },
				[5] = { "Start3" },
			},
			Air = { 1, 2, 3, 4 , 5},
			Hidden = { 5 },
			Class = {
				[1] = "Single",
				[2] = "Single",
				[3] = "Single",
				[4] = "Single",
				[5] = "Single",
			},
			Effect = "SkylightBeam",
		},
		[1] = {
			Cooldown = 6,
			Range = 50,
			Damage = 200,
			Price = 5000,
			Name = "Skylight",
		},
		[2] = {
			LevelName = "Nil",
			Cooldown = 5,
			Range = 50,
			Damage = 200,
			Price = 1350,
			Name = "Skylight",
			Invisible = { 0 },
		},
		[3] = {
			LevelName = "Nil",
			Cooldown = 4,
			Range = 50,
			Damage = 250,
			Price = 4150,
			Name = "Skylight",
			Invisible = { 1 },
		},
		[4] = {
			LevelName = "Nil",
			Cooldown = 8,
			Range = 75,
			Damage = 1000,
			Price = 10000,
			Name = "Skylight",
			Invisible = { 2 },
			Animation = 3,
		},
		[5] = {
			LevelName = "Nil",
			Cooldown = 16,
			Range = 75,
			Damage = 4000,
			Price = 25000,
			Name = "Skylight",
			Invisible = { 3 },
			Animation = 4,
		},
	},

	Anomaly = {
		ExtraInfo = {
			MaxLevel = 5,
			Class = {
				[1] = "Single",
				[2] = "Single",
				[3] = "Single",
				[4] = "Single",
				[5] = "Single",
			},
			Explosion = {
				[1] = { Effect = "NormalExplosion", Speed = 0.5, Grenade = "BlitzGrenade0", Sound = "SmallExplosion", AOE = 3 },
				[2] = { Effect = "NormalExplosion", Speed = 0.5, Grenade = "BlitzGrenade0", Sound = "SmallExplosion", AOE = 4 },
				[3] = { Effect = "BigExplosion", Speed = 0.4, Grenade = "BlitzGrenade2", Sound = "Explosion", AOE = 6 },
				[4] = { Effect = "BigExplosion", Speed = 0.3, Grenade = "BlitzGrenade2", Sound = "Explosion", AOE = 6 },
				[5] = { Effect = "BigExplosion", Speed = 0.25, Grenade = "BlitzGrenade2", Sound = "BigExplosion", AOE = 7 },
			},
			Effect = "Explosion",
		},
		[1] = {
			Cooldown = 1,
			Range = 3,
			Damage = 5,
			Price = 500,
			Name = "Anomaly",
		},
		[2] = {
			LevelName = "(?)",
			Cooldown = 1,
			Range = 3,
			Damage = 8,
			Price = 200,
			Invisible = {},
			Exlude = {},
			Name = "Anomaly",
		},
		[3] = {
			LevelName = "(?)",
			Cooldown = 0.75,
			Range = 3,
			Damage = 11,
			Price = 1000,
			Invisible = {},
			Exlude = {},
			Name = "Anomaly",
		},
		[4] = {
			LevelName = "(?)",
			Cooldown = 0.5,
			Range = 4,
			Damage = 17,
			Price = 1850,
			Invisible = {},
			Exlude = {},
			Name = "Anomaly",
		},
		[5] = {
			LevelName = "(?)",
			Cooldown = 0.3,
			Range = 4,
			Damage = 30,
			Price = 3000,
			Invisible = {},
			Exlude = {},
			Name = "Anomaly",
		},
	},

	None = {
		["ExtraInfo"] = {
			["MaxLevel"] = 1,
		},
		[1] = {
			["Cooldown"] = 0,
			["Range"] = 0,
			["Damage"] = 0,
			["Price"] = 0,
			["Name"] = "None",
		},
	},
}

return module